### ISSUE TITLE
Allowing user to set ete3 parsing mode

### ISSUE THREAD

**Issue by jmcbroome** [NicolaDM/phastSim#10]
Hello to the phastSim developers- I'm one of the developers for UShER (we appreciate you adding the UShER protobuf format as an output option!). 

We've been looking at some projects using phastSim conditioned on the UShER public tree and encountered an issue. matUtils outputs a newick formatted with internal node IDs (parsing mode 1 for ete3). phastSim can't take this format, since it's hardcoded to use parsing mode 0 for ete3 unless specific fixed mutations on some nodes are set (mutationsTSVinput), which we don't want to do for our purposes. 

We would greatly appreciate the addition of an argument which just sets the ete3 parsing mode. Something like --ete3Mode?

I can also look into making this change myself and opening a PR, if that would be helpful.

Thanks for all your hard work!

**Comment by NicolaDM** [comment]
Hi Jakob,
Indeed that should be very easy to implement! I wonder if it would be better to run a check automatically without requiring a new command line option, for example using a try-except when reading the tree, or even better check for the presence of ")*" substrings with "*" being an character different from ":" and ";".

**Comment by NicolaDM** [comment]
If you have the possibility to PR a fix, please go ahead!

**Comment by jmcbroome** [comment]
Dynamically trying to choose an appropriate parsing mode is interesting, but I think its probably better to give the user control of how the tree is parsed, like ete3 itself does. Obviously its up to you if you want to change how its handled in the future.

Pull request here: https://github.com/NicolaDM/phastSim/pull/11

**Comment by NicolaDM** [comment]
OK, merged now! Thanks!
