### ISSUE TITLE
phastSim output (mat.pb file) missing reference identifier

### ISSUE THREAD

**Issue by shlokanegi** [NicolaDM/phastSim#19]
Hi Nicola,

I am using phastSim to simulate mutations, by providing a Newick file as input. This is the command I'm using: -
```
phastSim --outpath phastSimA.1_output_scaled/ --seed 7 --treeFile subtree.nwk --reference NC_045512v2.fa \
    --createNewick --createMAT --createFasta --createInfo --createPhylip \
    --scale 0.000034 --alpha 1.0 --omegaAlpha 1.0 --codon \
    --eteFormat 1
```

Next, while converting this file to a VCF, it leads to an empty CHROM column. NOTE: I have used the [BTE](https://github.com/jmcbroome/BTE) package for the same.
```
##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  England/CAMB-7BC93/2020|FR994567.1|202
        259     A259G   A       G       .       .       AC=4;AN=214     GT      0       0       0       0
        362     G362T   G       T       .       .       AC=1;AN=214     GT      0       0       0       0
        984     G984T   G       T       .       .       AC=1;AN=214     GT      0       0       0       0
        1013    G1013T  G       T       .       .       AC=1;AN=214     GT      0       0       0       0
        1479    C1479T  C       T       .       .       AC=214;AN=214   GT      1       1       1       1
        1498    C1498T  C       T       .       .       AC=1;AN=214     GT      0       0       0       0
        1595    G1595T  G       T       .       .       AC=2;AN=214     GT      1       1       0       0
        2072    G2072T  G       T       .       .       AC=214;AN=214   GT      1       1       1       1
        2801    G2801T  G       T       .       .       AC=1;AN=214     GT      0       0       0       0
        2815    T2815C  T       C       .       .       AC=1;AN=214     GT      0       0       0       0
        3529    T3529C  T       C       .       .       AC=1;AN=214     GT      0       0       0       0
        5235    A5235G  A       G       .       .       AC=1;AN=214     GT      0       0       0       0
        5678    G5678T  G       T       .       .       AC=1;AN=214     GT      0       0       0       0
        6485    G6485A  G       A       .       .       AC=1;AN=214     GT      0       0       0       0
```
It appears to occur due to the `sars-cov-2_simulation_output.mat.pb` file lacking the reference genome information. See below -
```
^H<98>^P^P^B^X^B"^A^C
^G^HÝ¦^A"^A^B
^K^H°<8c>^A^P^B^X^B"^A^C
^K^HÜ¨^A^P^C^X^C"^A^A

^Hý7^P^A^X^A"^A^C
^K^H<99>¹^A^P^A^X^A"^A^C
```

**Comment by willboulton** [comment]
Hi Shloka, 

Since I was the one working on adding the MAT format, perhaps I'd be the best person to try to fix this issue. For the MAT output format I had tried to copy the same as in matUtils - which I think uses this protocol buffer file: https://github.com/yatisht/usher/blob/master/parsimony.proto - this has a value for 'chromosome' though the comment says it's unused. 

I had tried to create the same MAT format to be compatible with matUtils - if you use that tool do you know whether it actually adds a chromosome string? If so it makes sense to be consistent with it - which should be easy to add to the MAT.

Perhaps a quick fix in the meantime would just be to change the vcf in bash as post-processing!

Cheers, 
Will

**Comment by jmcbroome** [comment]
The comment in the proto is significantly out of date- [UShER/matUtils reads the chromosome name from the mutations in the protocol buffer](https://github.com/yatisht/usher/blob/master/src/mutation_annotated_tree.cpp#L569). phastSim should be updated for consistency.

**Comment by willboulton** [comment]
Thanks Jakob! 

The last commit should have fixed this - I have also updated the pypi repository. phastSim uses the ID string from the input fasta reference file as default, otherwise you can set your own name using --chromosomeName
